Feature/fix meta class hierarchy
smn-ailab/lift-learn pull request #1
Opened 2019-02-12 06:18 UTC by usaito

- meta_model moduleの抽象基底クラスをbase.pyにあるUpliftModelInterfaceに統一しました
    - 今後他のアルゴリズムを実装する際もこの基底クラスに準じたinterfaceで実装するつもりです
- TMAを削除し, SMAに統一しました. SMAは2以上の任意の介入数を扱うことができます.
    - predict_iteメソッドの返り値は, base treatmentに対する各treatmentのiteなので, columns数が (treatmentの数 - 1)となります.
- TOMとSDRMの目的変数変換は, _transform_outcome関数で一貫して行うようにしました.
    - TOMはSDRMの変数変換でmu=0, gamma=0とした場合なので, 引数で調整しています.

2019-02-14 02:34 UTC, hasoya requested changes
気になったところコメントつけました。具体的な実装をイメージできないところは聞きに来てください。

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +def _transform_outcome(y: np.ndarray, w: np.ndarray, ps: np.ndarray,
SMAでは使わないのにここにあるの変なんで、Transform Outcomeを使うクラス内に入れちゃってください

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +        self.fitted_po_models_: list = []
`fit`を呼ばすに`predict`呼んでしまうケースに備えて、例外投げられるようにした方がいいです。いまだと129行目でIndexError投げて死にます。初期値をNoneにしてそれを見て例外を投げるか、空リスト見て例外投げるか、どちらでも良いと思います。

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +        _extented_pred_ite = np.concatenate([np.zeros((pred_ite.shape[0], 1)), pred_ite], axis=1)
「ite予測 → ベストの介入選択」の流れは同じなので、それを基底クラスのpredictに実装しておいた方がいいのでは？

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +        _extented_pred_ite = np.concatenate([np.zeros((pred_ite.shape[0], 1)), pred_ite], axis=1)
つまり、`fit`と`predict_ite`だけを各具象クラスで実装すればよいってことですね

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +                pred_ite[:, trts_id] = model.predict_proba(X)[:, 1] - pred_baseline
fitted_po_modelのindexは1からなのに、pred_iteのindexは0からになってしまっていてindexずれてません？
`ndim == 1` のときを特別扱いしなければならない理由もよくわからない…

`len(fitted_po_models_) >= 2`なのであれば、

```python
baselines = []
for idx, model in enumerate(self.fitted_po_models):
    ites = model.predict_proba(X)[:, 1]
    if idx == 0:
        baselines = ites
    else:
        pred_ite[:, idx - 1] = ites - baselines
```

の方がよさそう

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SMARegressor(BaseEstimator, UpliftModelInterface):
これらとclassifierの違いって`predict`を呼ぶか`predict_proba`を呼ぶかだけの違い？それならそこだけ変える実装にした方がよいと思います。相当Code Duplicationが発生してしまっているので

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +        w : array-like, shape = [n_samples]
TOMってnum_treats = 2のみですよね？その旨は書いた方がいいかも。それより多いのが来たらinitで例外なげましょう

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +    [1] Yuta Saito, Hayato Sakata, and Kazuhide Nakata. "Doubly Robust Prediction
ほこらしい :+1:

2019-02-14 02:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
これの構成もSMAと同じ？

2019-02-14 02:48 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +def _transform_outcome(y: np.ndarray, w: np.ndarray, ps: np.ndarray,
TOM, SDRMClassifier, SDRMRegressorで同じものを使うので各クラスに実装するのではなく外に出して関数にしたのですが、クラスに入れた方が良いですか？

位置についてはSMAの後に来るよう修正します

2019-02-14 02:51 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +def _transform_outcome(y: np.ndarray, w: np.ndarray, ps: np.ndarray,
TOMもSDRMもPropensity basedなモデルなのでさらにそれに対応する基底クラス作ってそこに放り込むとか

2019-02-15 01:29 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +                pred_ite[:, trts_id] = model.predict_proba(X)[:, 1] - pred_baseline
SMAでは2段階以上の値を持つ介入を扱えます。
また各介入のITEは```idx=0```のbaseline介入からの差分で定義しているので
```idx=0```の介入のITEは全てのデータで0になるため返り値のarrayのcolumn数は
```(num_trts - 1)```としています。（全て0のcolumnをあえて含む必要はないかなと思いました。）
したがって、```num_trts=2```の場合、

```pred_ite[:, idx - 1]```

でエラーとなってしまうのですが、pred_iteを定義する部分を変更し、

```pred_ite = np.array( (num_data, num_trts) )```

とした上で、坂田さんに書いていただいたコードでpred_iteに予測値を埋め、

```return pred_ite[:, 1:]```

とするのがいいかなと思ったのですが、問題ないでしょうか？

2019-02-15 01:31 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +def _transform_outcome(y: np.ndarray, w: np.ndarray, ps: np.ndarray,
わかりました、ではbase.pyにUpliftModelInterfaceとBaseEstimatorを親クラスにもつPropensityBasedModelというクラスを新たに作ってみます

2019-02-15 01:33 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
SDRMはSMA的な要素もTOM的な要素も持つため完全にどっちの構成と同じとは言えないのですが、
proxy outcomeを作った上でbase modelを学習するという思想に基づくとTOMと同じ系統に属すると考えるのが自然だと思っています

2019-02-15 01:34 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +                pred_ite[:, trts_id] = model.predict_proba(X)[:, 1] - pred_baseline
`pred_ite[:, idx - 1]`でエラーになる理由が分からないのですが…ぼくの書いたコードでは`idx == 0`のときはbaselineを保存するだけで、実際にpred_iteに値を詰めるのは`idx >= 1`のときになっています。

2019-02-15 01:34 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +class SMARegressor(BaseEstimator, UpliftModelInterface):
ここだけ実装のイメージが湧いていないです...
SMA用の基底クラスを別途実装してそれを活用する感じでしょうか？

2019-02-15 01:37 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
言葉足らずでした、構成というのは差分がclassifier → predict_probaを呼び、regressor → predictを呼んでいるというところだけなのは共通なのかという質問でした。

2019-02-15 01:40 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +                pred_ite[:, trts_id] = model.predict_proba(X)[:, 1] - pred_baseline
確認したところエラーを吐くと思っていた部分が問題なかったので```ndim```で場合分けする必要がなかったです。確認不足でした、すみません。

2019-02-15 01:40 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
そういう意味でしたら、その通りです

2019-02-15 02:00 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SMARegressor(BaseEstimator, UpliftModelInterface):
そんな感じです。

```python
class SMACommon(BaseEstimator, UpliftModeliInterface):
    def predict_ite(X, is_classifier):
        ...
        pred_ite = model.predict_proba(X) if is_classifier else model.predict(X)
        ...

class SMAClassifier(SMACommon):
    def predict_ite(X):
        return predict_ite(X, is_classifier=True)

class SMARegressor(SMACommon):
    def predict_ite(X):
        return predict_ite(X, is_classifier=False)
```

こんなイメージです

2019-02-15 02:01 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SMARegressor(BaseEstimator, UpliftModelInterface):
クラスの継承関係で理論の関係性が記述できると美しいコードです

2019-02-15 02:03 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
SMA側に改善案貼りました

2019-02-15 02:10 UTC, usaito commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
ありがとうございます。とするとSDRMについては、

``` UpliftModelInterface -> PropensityBasedModel -> SDRMCommon -> SDRMClassifier or SDRMRegressor ```

という継承関係になるイメージなのですが、認識にズレはないでしょうか？

2019-02-15 02:10 UTC, hasoya commented on lflearn/meta_model/meta_model.py
> +class SDRMRegressor(BaseEstimator, UpliftModelInterface):
あってますー

2019-02-15 06:21 UTC, usaito commented
PropensityBasedModelというクラスを新たに実装するつもりでしたが、手法の設計思想的にTransformationBasedModelの方が名前として適切だと思ったのでそうしました。また、その設計思想に属するCVTもこのクラスを継承しています。
それ以外は、基本的にご指摘いただいた通りに修正したつもりです。

2019-02-18 01:08 UTC, usaito commented
もう一点変更点がありました。

```python
class SMACommon(BaseEstimator, UpliftModeliInterface):
    def predict_ite(X, is_classifier):
        ...
        pred_ite = model.predict_proba(X) if is_classifier else model.predict(X)
        ...
```

と例をいただいておりましたが、基底クラスから引数に```is_classifier```が増えたため、atomに怒られました。よって、```__init__```に```is_classifier```を持たせることにしました。

2019-02-18 01:16 UTC, hasoya requested changes
少しだけコメントつけました。だいぶコードがすっきり短くなりましたね。

2019-02-18 01:16 UTC, hasoya commented on lflearn/base.py
> +            raise MultiTreatmentError("treatment assignments shoul be binary values")
typo

2019-02-18 01:16 UTC, hasoya commented on lflearn/base.py
> +        _extented_pred_ite = np.concatenate([np.zeros((pred_ite.shape[0], 1)), pred_ite], axis=1)
これって何を意図したどういう操作ですか？コメントつけてください。

2019-02-18 01:16 UTC, hasoya commented on lflearn/base.py
> +class UpliftModelError(Exception):
exceptionは一箇所で管理すべきです。sklearnのそれを参考に

https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/exceptions.py

2019-02-19 04:50 UTC, usaito commented
コメントありがとうございます。再度修正を加えました。

```python
_extented_pred_ite = np.concatenate([np.zeros((pred_ite.shape[0], 1)), pred_ite], axis=1)
```
こちらですが, pred_iteにはbaseline介入のITEが（全てゼロであるため）含まれていませんが、最適な介入を導く場面ではbaseline介入も考慮に入れた上でargmaxを取りたいためこのような処理を入れています。

```# the ITEs of baseline treatment are zero.```

と入れてみましたが、不十分でしょうか？

2019-02-20 01:03 UTC, hasoya commented
`# Adding all zero value columns to choose the best treatment including baseline one.`

でどうでしょう。

2019-02-20 01:04 UTC, hasoya approved these changes
他は問題ないのでapproveします。英語だけ直していただければ。

2019-02-20 02:16 UTC, merged